name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: make init && make
    - name: make tests
      run: cd tests && cmake -H. -Bbuild && cd build && make && ./tests
