name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git clone https://github.com/catchorg/Catch2.git
    - run: cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF
    - run: cd Catch2 && sudo cmake --build build/ --target install
      
    - name: make
      run: make init && make debug && sudo make install
    - name: make tests
      run: cd tests && cmake -H. -Bbuild && cd build && make && ./tests
    - name: Make coverage report
      run: mkdir -p docs/html && make coverage
    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./docs/html/coverage
